[package]
name = "randnote"
version = "0.2.0"
edition = "2021"
description = "CLI tool to manage plain text notes"
license = "MIT"
repository = "https://github.com/JaredHeinrich/randnote"
readme = "README.md"
exclude = [
    "./completions/zsh.reference"
]

[[bin]]
name = "rn"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
chrono = {version ="0.4"}
serde = {version = "1.0", features = ["derive"]}
toml = {version = "1.0"}
anyhow = {version = "1.0"}
thiserror = {version = "2.0"}

[build-dependencies]
clap = { version = "4.6", features = ["derive"] }
clap_complete = {version = "4.6"}
anyhow = {version = "1.0"}

[lints.clippy]
pedantic = { level = "warn" }
style = { level = "warn" }
complexity = { level = "warn" }
perf = { level = "warn" }

unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
print_stdout = "warn"
print_stderr = "warn"
indexing_slicing = "warn"
